name: expense_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  connectivity_plus: ^6.1.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  get: ^4.7.2
  http: ^1.5.0
  intl: ^0.20.2
  logger: ^2.6.1
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
